/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __JNITester__
#define __JNITester__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_JNITester_callMe (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __JNITester__ */
